### ISSUE TITLE
async_rct_complete is not reliable

### ISSUE THREAD

**Issue by sunaku** [osyo-manga/vim-monster#2]
When using this setting, completion menu is slower and doesn't appear consistently. :crying_cat_face:

``` vim
" Set async completion.
let g:monster#completion#rcodetools#backend = "async_rct_complete"
```

Disabling the setting makes the completion menu faster and reliable (always appears). :sweat_smile:

**Comment by osyo-manga** [comment]
hmmm... Please tell me for example completion.

**Comment by sunaku** [comment]
I tried the `Test.new.homu.mami` example shown on this plugin's homepage: 
1. Insert `Test.` and menu appears; choose "new".
2. Insert `.` and menu does not appear (sometimes); insert `homu`.
3. Insert `.`  and menu does not appear (sometimes); insert `mami`.

``` ruby
class Test
  def homu
    Test.new
  end

  def mami
    puts "mami"
  end
end

Test.new.homu.mami
```

**Comment by osyo-manga** [comment]
Thanks.
Please tell me `'updatetime'` value and vim-monster setting.

**Comment by sunaku** [comment]
I have `updatetime=500` due to my neocomplete setting ([complete file here](https://github.com/sunaku/.vim/blob/bundle/config/bundle/complete/neocomplete.vim#L11-L14)):

``` vim
" User must pause before completions are shown.
" https://www.reddit.com/r/vim/comments/2xl33m
let g:neocomplete#enable_cursor_hold_i = 1
let g:neocomplete#cursor_hold_i_time = 500 " milliseconds
```

My vim-monster setting is the same as the example on the homepage:

``` vim
" Set async completion.
let g:monster#completion#rcodetools#backend = "async_rct_complete"

" Use neocomplete.vim
let g:neocomplete#force_omni_input_patterns = {
\   'ruby' : '[^. *\t]\.\|\h\w*::',
\}
```

**Comment by osyo-manga** [comment]
Sorry reply is delayed.
Please update neocomplete.vim and next setting.

``` vim
" let g:neocomplete#force_omni_input_patterns = {
" \   'ruby' : '[^. *\t]\.\|\h\w*::',
" \}

" Use g:neocomplete#sources#omni#input_patterns
let g:neocomplete#sources#omni#input_patterns = {
\   'ruby' : '[^. *\t]\.\w*\|\h\w*::',
\}
```

**Comment by sunaku** [comment]
:+1: That solved the problem, thanks! :bow:

**Comment by osyo-manga** [comment]
OK :)
