### ISSUE TITLE
No completion at all

### ISSUE THREAD

**Issue by kellino** [osyo-manga/vim-monster#3]
Hello!

I've installed rcodetools in ~/.gem and used the settings in my ~/.vimrc as described on the main page, but I get no completion at all, not even a pop-up menu (even if I manually enter <C-x><C-o>).
Instead, I get "monster.vim - empty completion" in the commandline. Presumably this means that vim isn't finding rcodetools? It's in my PATH as rct-complete so I'm not sure what the problem is...
Any ideas?

**Comment by kellino** [comment]
Sorry, forgot to add that I'm using neocomplete on linux. I don't seem to have any problems with autocomplete using other plugins. Thanks

**Comment by osyo-manga** [comment]
hi.
Please tell me monster.vim and neocomplete.vim setting.

**Comment by kellino** [comment]
if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.ruby = '[^._\t].\w_|\h\w*::'

" Use neocomplete.vim
let g:neocomplete#sources#omni#input_patterns = {
\   "ruby" : '[^. _\t].\w_|\h\w*::',
}
let g:monster#completion#rcodetools#backend = "async_rct_complete"

to test it, I used the example as given on your page "Test.new.homu." etc/

**Comment by osyo-manga** [comment]
hmm...
Please disable `g:neocomplete#force_omni_input_patterns`setting.

``` vim
" Disable g:neocomplete#force_omni_input_patterns
" if !exists('g:neocomplete#force_omni_input_patterns')
" let g:neocomplete#force_omni_input_patterns = {}
" endif
" let g:neocomplete#force_omni_input_patterns.ruby = '[^.\t].\w|\h\w*::'

" Use g:neocomplete#sources#omni#input_patterns only
let g:neocomplete#sources#omni#input_patterns = {
\ "ruby" : '[^. \t].\w|\h\w*::',
}
```

**Comment by kellino** [comment]
Done, but still nothing I'm afraid. Same error message: empty-completion. Not sure what the problem is...

**Comment by osyo-manga** [comment]
hmm...
Use `rct_complete` and disable neocomplete.vim.

``` vim
let g:monster#completion#rcodetools#backend = "rct_complete"
```

**Comment by kellino** [comment]
Problem solved. Nothing wrong with the ~/.vimrc or the plugin. For some reason, even though it was in the system path, vim wasn't finded rcodetools (I'm on arch linux). I simply reinstalled it system-wide and now it's working perfectly! どうもありがとう (I hope that's correct!)

**Comment by osyo-manga** [comment]
OK :)
