### ISSUE TITLE
一番下の候補が自動で選択される

### ISSUE THREAD

**Issue by NigoroJr** [osyo-manga/vim-monster#4]
こんにちは。vim 7.4.775で`noinsert`, `noselect`が追加されたのと、それを反映したneocomplete.vimのアップデートでmonster.vimで一番下の候補が選択されるようになりました。

現在[この行](https://github.com/osyo-manga/vim-monster/blob/d854f61be14e927e3288a8cd620f3d336d5c6adf/autoload/monster/completion/rcodetools/async_rct_complete.vim#L42)を`"\<C-x>\<C-o>"`にして候補が勝手に選択されるのを防いでいるのですが(見当違いなことをしているかもしれませんが)、7.4.775にアップデートしていないユーザーもいることを考えると安易に変更しないほうがいいのかなと思い報告しました。

**Comment by osyo-manga** [comment]
ありがとうございます。
こちらの方でも少し調べてみます。

**Comment by NigoroJr** [comment]
すみません、最小限のvimrcを貼り忘れていました。以下がそれです。

``` vim
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))

set updatetime=500
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'osyo-manga/vim-monster', {
    \ 'depends': ['Shougo/neocomplete.vim', 'Shougo/vimproc.vim'],
    \ }
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#force_omni_input_patterns = {
      \ 'ruby': '[^. *\t]\.\w*\|\h\w*::'
      \ }

let g:monster#completion#rcodetools#backend = 'async_rct_complete'

call neobundle#end()
filetype plugin indent on
```

**Comment by osyo-manga** [comment]
あ、あと確認なのですが『neocomplete.vimを使用した場合のみ』この問題は発生するのでしょうか？

**Comment by NigoroJr** [comment]
はい。今まさかと思ってneocomplete.vimを入れずに試してみたところ、見事に下の候補が選択される問題がなくなりました……

**Comment by NigoroJr** [comment]
あと、`g:neocomplete#force_omni_input_patterns`を抜いた場合も大丈夫なようです。お恥ずかしいです……

**Comment by osyo-manga** [comment]
ありがとうございます。
単に Vim のバージョンによって処理を切り替えるだけというのは難しそうですね。

**Comment by NigoroJr** [comment]
うーん、neocomplete.vim側の問題みたいなので、もう少しよく調べてからissueを開こうと思います。申し訳ないです、お騒がせしました orz

**Comment by osyo-manga** [comment]
いえいえ、ありがとうございました。
