### ISSUE TITLE
Deoplete integration

### ISSUE THREAD

**Issue by smarquez1** [osyo-manga/vim-monster#6]
Is it possible to integrate vim-monster with [deoplete](https://github.com/Shougo/deoplete.nvim)? If so, how can I do it?

Thanks!

**Comment by lynndylanhurley** [comment]
I'd like to see this as well.

**Comment by sebastianvera** [comment]
+1 <3

**Comment by jhenahan** [comment]
This already works with deoplete for me.

``` vim
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
        \   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
        \}
```

**Comment by cj** [comment]
@jhenahan that works.  but the completion is always empty.

**Comment by linduxed** [comment]
It would be nice if this kind of instructions would be put in the README. The configuration written by @jhenahan necessitates the installation of the plugin `vimproc.vim`, which I'm not sure whether it's necessary/preferred.

**Comment by smarquez1** [comment]
@jhenahan: Thanks for the the info
@linduxed:  Here, I created a PR to address this issue,please coment: https://github.com/osyo-manga/vim-monster/pull/8

**Comment by pacuna** [comment]
I'm also getting empty completion with Ruby :(
