### ISSUE TITLE
"Empty completion" in strings

### ISSUE THREAD

**Issue by jhenahan** [osyo-manga/vim-monster#7]
When typing strings that contain `.`, the plugin reports "empty completion" and rings the bell. I've been messing around with the input pattern regex to try to avoid that, but I haven't gotten it to work, yet.

**Comment by cj** [comment]
I'm getting empty completion every time too.

**Comment by linduxed** [comment]
I seem to be having the same issue.

**Comment by trodrigu** [comment]
Same here.

**Comment by carakan** [comment]
recently I'm getting this same error

**Comment by matipan** [comment]
Same here

**Comment by osyo-manga** [comment]
Sorry for my late reply.
Please tell me plugin setting and Ruby code.
